### ISSUE TITLE
Best way to debug in production?

### ISSUE THREAD

**Issue by brandoncordell** [Studiosity/grover#110]
This gem has worked great for us so far but I'm no longer getting styles in production.

I'm preprocessing the html and when I debug the output of the page all of the link/script tags are correct and can be loaded in the browser without any issues. The content is fine and the time from screen to pdf is very quick so there's no timeout issues or lack of threads.

My controller setup hasn't changed much from #101 (although I no longer have `execute_script: false` in there of course).

**Comment by abrom** [comment]
So am I right in assuming you're calling to Grover directly rather than using the middleware?

You could dump the processed HTML into a file, then see that rendering that locally "works". 

One possibility if it works in other environments might be some form of firewalling in your production environment (ie say you were hosting the assets via a CDN that wasn't directly available on the production machine?). You can easily test this by requesting the assets from a terminal on the production machine.

**Comment by brandoncordell** [comment]
FWIW this appears to be intermittent since I got a message from one of our users that the problem was fixed (I hadn't yet touched the production server).

I grabbed the outputted HTML from our staging server (which was showing the same issue) and saved it to a local html file and it looked and worked as it should.

One strange note for some reason we have `overflow: hidden` on our body tag for this particular pdf layout, will that cause issues with puppeteer?

**Comment by abrom** [comment]
If it's intermittent then it sounds like you've got load/render timing issues. I see from your example you've specified `wait_until: networkidle0` which will wait until there are no network requests for 500ms. You could try use a different wait option (`load` or `domcontentloaded`). 

Another option would be to use the `wait_for_selector` (ie have some element added to the page with JS or made hidden/visible with CSS) or `wait_for_timeout` options. 

I haven't added support for the `waitForFunction` puppeteer method as yet but that might be another option
