### ISSUE TITLE
[Feature Proposal] Set content-disposition header with pdf filename

### ISSUE THREAD

**Issue by artur79** [Studiosity/grover#133]
When using middleware pdf is always returned inline and filename is e.g. "pdf.pdf" or "download.pdf" depends on action name or Rails' side. I'd like to add the feature that user can set filename in meta tag like **grover-filename** but I'v stucked in _middleware.rb_ file. How can I access **meta_options** from there ?

**Comment by abrom** [comment]
It feels like you're over complicating this?! You can set the content disposition header (or any header) in the "HTML" request made by the middleware and that will be passed back through to the response 😄 

Check out the `_call` method in the middleware. You can see the upstream response/headers are received, then the response converted. However the original headers (with some tweaks) are returned back down to the downstream processors!

Your suggestion would definitely be possible, I just don't think it's the right place for that sort of thing. As a thought exercise I can see (if the change was required) you would modify the `Grover` class to add an accessor for the processed `options`. Then move the grover instance creation from `convert_response` to `update_response` (and pass the instance through to `update_response` instead of the `response` itself). Finally pass through the `grover` instance to the `assign_headers` method where you could conditionally add the header. But again, better/simpler to just have your upstream "source" of the HTML add the header there!

**Comment by artur79** [comment]
It took me a while to get it but it works :) Let me leave it for others, or I may create README pull request if you think it may be valuable for other users

```
    respond_to do |format|
      format.pdf do
        render layout: 'pdf'
      end
      format.html do
        filename = "lorem_ipsum.pdf"
        response.headers['Content-Disposition'] = %(attachment; filename="#{filename}")
      end
    end
```

**Comment by silent-e** [comment]
You might also look into specifying it in the link you click, if that's the mechanism.  No need to set headers or anything like that.  And excellent browser support.  It's what I'm using.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/download
