### ISSUE TITLE
Render Background Image on every page

### ISSUE THREAD

**Issue by raghavmalawat** [Studiosity/grover#139]
Use Case: Need to add a background image at the centre of every page, like a watermark.

After reading a bit, tried using below styling, but this doesn't help. The image only appears on the first page, I guess due to the default pagination.

` body {
            background-image: url(http://img.freepik.com/free-vector/white-abstract-background_23-2148810113.jpg);
            background-position: bottom;
            background-attachment: fixed;
            background-repeat: repeat;
        }`

Is there any way we can achieve the same?

And if we can just render one single page long PDF that will work too (one background image will be fine in that case)

**Comment by abrom** [comment]
This would seem to solve your issue: https://stackoverflow.com/questions/56349789/how-can-i-add-a-watermark-to-a-pdf-that-is-generated-by-puppeteer

ie.
```
Grover.new('https://www.microsoft.com', execute_script: <<~SCRIPT).to_pdf('foo.pdf')
  const div = document.createElement('div');
  div.innerHTML = 'Watermark Text...';
  div.style.cssText = "position: fixed; bottom: 10px; right: 10px; background: red; z-index: 10000";
  document.body.appendChild(div);
SCRIPT
```
You could put what ever you want in the HTML.

I don't see any reason why this wouldn't work in the source of the HTML too (ie using `position: fixed` instead of the `background*` attributes.)

**Comment by raghavmalawat** [comment]
Any way we can have a single page long PDF? @abrom

**Comment by abrom** [comment]
Yes, it should be possible. Can you tell me what you've tried yourself already?

**Comment by raghavmalawat** [comment]
I've tried [https://stackoverflow.com/questions/55610614/full-page-pdf-in-puppeteer](https://stackoverflow.com/questions/55610614/full-page-pdf-in-puppeteer ) and changing some grover viewport configs, being new to rails also delays how to write the puppeteer configs in grover sometimes.

**Comment by abrom** [comment]
you can definitely do this with the `screenshot` method (ie `to_png` or `to_jpeg`) using the `full_page: true` option:

See https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagescreenshotoptions

You wouldn't be able to use most of the solutions you linked to because they require evaluating the content height after rendering the page and before extracting the resultant PDF (or image). You would instead need to fork the Grover codebase and modify the [processor.js](https://github.com/Studiosity/grover/blob/main/lib/grover/js/processor.js) to fetch and assign the various other properties as you need.

**Comment by raghavmalawat** [comment]
> This would seem to solve your issue: https://stackoverflow.com/questions/56349789/how-can-i-add-a-watermark-to-a-pdf-that-is-generated-by-puppeteer
> 
> ie.
> 
> ```
> Grover.new('https://www.microsoft.com', execute_script: <<~SCRIPT).to_pdf('foo.pdf')
>   const div = document.createElement('div');
>   div.innerHTML = 'Watermark Text...';
>   div.style.cssText = "position: fixed; bottom: 10px; right: 10px; background: red; z-index: 10000";
>   document.body.appendChild(div);
> SCRIPT
> ```
> 
> You could put what ever you want in the HTML.
> 
> I don't see any reason why this wouldn't work in the source of the HTML too (ie using `position: fixed` instead of the `background*` attributes.)

Using `position:absolute` works, thanks @abrom
