### ISSUE TITLE
Heroku slug size - best to use puppeteer core?

### ISSUE THREAD

**Issue by darylpdavies** [Studiosity/grover#148]
Following on from Issue #91 

I'm struggling to get my slug size under 500MB for Heroku. Is it best to use puppeteer with the "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" setting to true, or is it now better to use puppeteer-core?

Assuming the Chrome buildpack is the best replacement?

**Comment by abrom** [comment]
Either should work. Although If you're going to use `puppeteer-core` then you'll need to use the branch I've created to load it: https://github.com/Studiosity/grover/tree/try-load-puppeteer-core

I haven't done much testing of this branch which is why I haven't merged it down. Happy to take feedback if this is a useful feature of course!

I can't speak to much on the topic of Heroku and Chrome buildpacks etc. I suspect searching for `puppeteer` and `heroku` would yield the results you're after though.. Of course I'd be more than happy to accept a PR to improve on the Heroku documentation within Grover if it is out of date 😄

**Comment by abrom** [comment]
This is supported as of [v1.1.7](https://rubygems.org/gems/grover/versions/1.1.7)
