### ISSUE TITLE
Using grover through import maps (Rails 7)

### ISSUE THREAD

**Issue by aliciapaz** [Studiosity/grover#149]
I've been trying to setup the gem in a rails 7 app using the default asset pipeline (importmaps). However, I keep running into the same error: 

```
Cannot find module 'puppeteer'. You need to add it to '/Users/my-user/my-app/package.json' and run 'npm install'
```

According to Puppeteer's documentation:

> Starting from v3.0.0 Puppeteer starts to rely on Node 10.18.1+. All examples below use async/await which is only supported in Node v7.6.0 or greater.

Although I've used other node libraries through `importmap` with no issues before,  I must be missing something now.

Would someone confirm if it's possible to use Grover without node installed?

**Comment by abrom** [comment]
Hmm that error message suggests you **do** have `node` installed, but instead don't have `puppeteer` installed. Also, not really following how this is a Rails 7 specific issue? In the context of `importmap`, you're specifying logical names for packages that the **client** (web browser) is downloading directly from a CDN. I would say you've been using other JavaScript libraries through `importmap`, not `node` libraries :smile:.  For Grover/Puppeteer the node modules are being loaded server side, and considering the size of the module, definitely not something you'd want dynamically loaded from a CDN (which i don't see would be practical, or possible with the vanilla toolsets).

You should be able to fix this by simply installing puppeteer in your project root (but likely after you've initialised the NPM project):
```bash
npm install puppeteer
```

If it were a `node` install issue you would have got something like:
```
Errno::ENOENT (No such file or directory - node)
```

If you don't want to install `puppeteer` in the root of your Rails project, you can overload the path in which Grover will try load `puppeteer`:

```
# config/initializers/grover.rb
Grover.configure do |config|
  config.root_path = '/some/path/other/than/my/project/root'
end
```

HTH

**Comment by watsaket00** [comment]
on my macOS, I install puppeteer on global by
```bash
npm i -g puppeteer
```

and in 'config/initializers/grover.rb' be like this
```ruby
# config/initializers/grover.rb
Grover.configure do |config|
  config.options[:root_path] = "#{`npm prefix -g`.strip}/lib"
end

```
My lib version is
```
grover (1.1.1)
puppeteer(16.1.0)
node(14.17.0)
```

**Comment by m3thom** [comment]
For Heroku, I have to tweak it a little bit.
After installing `node` and `puppeteer` as following https://github.com/Studiosity/grover#running-on-heroku

`heroku buildpacks:add heroku/nodejs`

`heroku buildpacks:add`

1. Add a `package.json` file to your project. We still use `import maps` this is only for `Heroku` auto-detection. 
Your `package.json` file should look like this.
```json
{
  "name": "for-heroku-only",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "puppeteer": "^16.1.0"
  }
}

```

2.  Make sure to explicitly create a `Procfile`. Your `Procfile` should be like something like this.
```
web: bin/rails server -p ${PORT:-5000} -e $RAILS_ENV
```

3. Make change to `config/initializers/grover.rb`
```ruby
Grover.configure do |config|
.
.
.
  if ENV.fetch("IS_HEROKU", false)
    config.options[:launch_args] = %w(--no-sandbox)
  else
    config.options[:root_path] = "#{`npm prefix -g`.strip}/lib"
  end

end
```

4. Set `IS_HEROKU` var to `true` in your `Heroku` app settings page.
5. Deploy your app to `Heroku`

**Comment by seanbjornsson** [comment]
I also am not using webpack and so didn't want to move away from importmap just for Grover.
I feel like this issue is resolved and can be closed? I can confirm that the solution to use a heroku-only package.json worked great form me, alongside using a globally installed node locally and updating the root path as advised.

A few comments
- @m3thom you should update your comment to correctly indicate the [puppeteer buildpack](https://elements.heroku.com/buildpacks/jontewks/puppeteer-heroku-buildpack). Right now the line just ends before you indicate what buildpack it is.
- If you're using the `runtime-dyno-metadata` lab you can use `HEROKU_APP_ID` instead of setting a new `IS_HEROKU` config
- If you're using Puppeteer 19.x then you need to include a config file to tell node to cache the browsers in `app_dir/.cache/` by adding a new `project-directory/.puppeteerrc.cjs` file as described [here](https://pptr.dev/guides/configuration#changing-the-default-cache-directory) (and in the Grover readme).
```js
const {join} = require('path');

/**
 * @type {import("puppeteer").Configuration}
 */
module.exports = {
  // Changes the cache location for Puppeteer.
  cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};
```

The following is a little off topic, but I figured it would be helpful to the next person who arrives at this thread to set up Grover on Heroku.
If everything is all set up right you should be able to log onto a dyno and see a `.cache` folder that is created from `npm install`, as directed by `.puppeteerrc.cj`.
If you DONT, as I did not, there are two reasons that I ran into:
1) You don't have a `.puppeteerrc.cj` file as indicated above. In this case, you may also need to see number 2.
2) You do have a `.puppeteerrc.cj` but added it after your initial deploy with the nodejs buildpack and the package.json. In this case, heroku/nodejs buildpack will treat puppeteer as already installed and therefore not install it and not create the .cache directory.

To fix issue 2 I did the following:
-  Update package.json to have no dependencies
- `heroku config:set NODE_MODULES_CACHE=false`
- `heroku plugins:install heroku-builds`
  `heroku builds:cache:purge`
- `git commit -- -m "Purge node modules"`
- Add puppeteer back to package.json, commit, and push

I hope this helps the next person dealing with Heroku caches crushing thier Grover dreams!
