### ISSUE TITLE
Background color not showing

### ISSUE THREAD

**Issue by jjf21** [Studiosity/grover#152]
Hi, I just started using Grover and while most of my css so far render correctly, the background-color does not

```ruby
    style_tag_options = [{ content: 'h1 {background-color: red; color: blue;}' }]
    pdf = Grover.new("<html><body><h1>Hello</h1></body></html>", style_tag_options: style_tag_options).to_pdf
    send_data pdf, type: "application/pdf"
```

return

<img width="1256" alt="Capture d’écran 2022-03-25 à 10 27 43" src="https://user-images.githubusercontent.com/29787388/160093881-a8a8c6d0-b16c-44f3-bea1-5e73e153b32a.png">

Config:
rails 7.0.2.3
grover 1.1.1
puppeteer 13.5.1

I am missing something ?

**Comment by abrom** [comment]
Hi @jjf21

It sounds like you need to look at the [print-color-adjust](https://developer.mozilla.org/en-US/docs/Web/CSS/print-color-adjust) CSS property.. specifically using the `exact` value. This isn't a Grover thing.. it's a "print" thing. Browsers won't show background colours by default when printing because they assume that and background colour won't print particularly well. But the `print-color-adjust: exact` style tells the browser that you know what you're doing and to just print it like you've styled it. Grover "prints" the page to PDF, thus why this applies 😉 

HTH

**Comment by abrom** [comment]
Feel free to submit a PR to update the README if you believe it could be improved Re this topic 😄

**Comment by rsl** [comment]
heh found it https://www.api2pdf.com/background-color-on-header-footer-in-headless-chrome/ 
```
-webkit-print-color-adjust: exact;
```
