### ISSUE TITLE
Grover::Error Worker process failed - "Errno::EPIPE Broken pipe - Can't read from worker"

### ISSUE THREAD

**Issue by WillTaylor22** [Studiosity/grover#157]
I have an intermittent failure with Grover

`Grover::Error Worker process failed`

The error message reads "Errno::EPIPE Broken pipe - Can't read from worker"
This occurs in lib/grover/processor.rb in call_js_method

When this happens, the rails process tends to crash. I can usually re-run the process and it runs successfully.

Any idea what is causing this, or how to fix it?

**Comment by abrom** [comment]
would need to have some more context about how you're using it to comment further.. but in short you would see that error when the Puppeteer worker process has died/quit without returning any content.

The actual error returned will be of the form:
```
Worker process failed:
<the reason given by the worker from stderr (if any)>
```
(you appear to have missed the colon, as well as any possible error returned by the Puppeteer worker?? - although per above, that could be optional)

> The error message reads "Errno::EPIPE Broken pipe - Can't read from worker"
This occurs in lib/grover/processor.rb in call_js_method

Are you trying to say that you've added some debug steps in the Processor ? Because that error message should be caught within the `call_js_method` method and not exposed any further (the worker process failed message is raised in its place!)

Some follow-up questions:
* Is this in a production environment, or development?
* Is there any chance you're simply running out of memory? That could very much show up as something like this..
* Can you share any details about the Rails process crash? There might be some inter-related reasons there..
* It is entirely possible that the Rails server crashing is causing this.. ie is this cause or effect?
* Are you passing through a URI? or raw HTML to the processor? If it is raw HTML, roughly how large is it?

**Comment by WillTaylor22** [comment]
Hey Abron, thanks for the quick response.

Yes, so it actually says "Worker process failed:" but there is nothing after the colon.

I haven't added any debug step in the processor. You're absolutely right, looking at the stack trace the issue was only caught in call_js_method, but was likely caused in the processor convert method.

Here's the full stack trace.

```Errno::EPIPE: Broken pipe - Can't read from worker
  from grover (1.1.1) lib/grover/processor.rb:83:in `call_js_method'
  from grover (1.1.1) lib/grover/processor.rb:20:in `convert'
  from grover (1.1.1) lib/grover.rb:50:in `to_pdf'
  from app/services/tax_tribs/case_details_pdf.rb:22:in `generate'```

Regarding your followups:
- This is happening in prod.
- It certainly could be a memory issue, as it's intermittent and it crashes the entire rails process. I'm not sure how to completely prove it's a memory issue and not something else.
- Details about the process crash: not a lot to go on. Here are the environment details:
OS: Linux #126~16.04.1-Ubuntu SMP
Ruby Version: 2.7.6p219
- Re: Cause or effect - This only happens when running the Grover line `Grover.new(html, format: 'A4').to_pdf`, and is reproducible (eventually - if you try repeatedly).
- Passing in raw HTML. Typically HTML is 4000 characters long, final PDF is about 40kb. At the top end, PDFs may be 2x as large.

All in all, it could be a memory issue, it just seems surprising given the file sizes involved are not massive.

**Comment by abrom** [comment]
Right, so sounds like what ever is happening the worker process isn't outputting anything to stderr.

Definitely strange that Rails is also dying. Can you provide any insight as to what the Rails logs suggest about its reason for crashing?

HTML size wouldn't seem to be an issue (was thinking more if it were in the 10s or 100s of MBs there might be something weird going on there)

Can you try reproduce the fault and watch some the system stats (say `top`)? Either using the Rails console, or something like `ab` (Apache HTTP benchmarking tool)? Something tells me that the Rails log will likely give you more insights..

I've just tried generating 2000 PDFs from static and remote content (each type concurrently), but no errors.. Reproducibility will be key.

**Comment by WillTaylor22** [comment]
Hmm. I've just been able to create 50 of the heaviest PDF with no issues, one which I was able to reproduce this issue with yesterday. Really frustrating.

I can only conclude that there is a memory leak elsewhere in the app, and Grover has occasionally been the straw that broke the camels back and caused it to totally fail.

Nothing else in the logs...

You can close this. I'll post again if I can reproduce, and I'll get the system stats at the same time. Apologies for the disturbance.
