### ISSUE TITLE
any tips on running this on heroku ?

### ISSUE THREAD

**Issue by koenhandekyn** [Studiosity/grover#16]
current error:

Schmooze::JavaScript::Error in NodesController#register
Failed to launch chrome! /app/node_modules/puppeteer/.local-chromium/linux-662092/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by abrom** [comment]
Have you installed puppeteer ? Google suggests this buildpack (or something like it) is necessary:

https://elements.heroku.com/buildpacks/jontewks/puppeteer-heroku-buildpack

**Comment by koenhandekyn** [comment]
exact ! 

    heroku buildpacks:add jontewks/puppeteer

in my case buildpack order was relevant (ruby needs to be after it for example). 

but it doesn't seem sufficient, one needs to add extra arguments to puppeteer when launching as documented it seems

            const browser = await puppeteer.launch({
                args: ['--no-sandbox', '--disable-setuid-sandbox']
            });

**Comment by koenhandekyn** [comment]
it looks like it matches the CI code switch :) - i'll give it a try :)

**Comment by koenhandekyn** [comment]
wrap up

- heroku buildpacks:add jontewks/puppeteer
- heroku config:set CI=true

proposal : it would be somewhat more clear to use PUPPETEER_NO_SANDBOX as ENV variable name (as the usage is not CI specific)

**Comment by abrom** [comment]
Excellent!

I'm certainly not fixed on the current ENV setup. It's only using the current variable because that's what TravisCI provides by default. It is possible to add new ENVs in the .travis.yml config file however.

I'd certainly welcome a PR, especially if you could document the steps needed to make it work! If the steps need some more details, maybe create a `heroku_setup.md` and link to it in the readme.md ?

**Comment by koenhandekyn** [comment]
thanks for the feedback. will look into a good PR :)
