### ISSUE TITLE
CSS is not taken in account when generating the PDF

### ISSUE THREAD

**Issue by jetienne** [Studiosity/grover#199]
I am using Rails 7.0.7, grover (1.1.5). 

My controller code is :
```ruby
 def show
    @contract = Contract.find(params[:id])
    html = render_to_string layout: 'application'

    respond_to do |format|
      format.pdf do
        pdf = Grover.new(html, format: 'A4').to_pdf
        send_data pdf, filename: @contract.id, type: 'application/pdf', disposition: 'inline'
      end
    end
  end
```

The layout is the following:
```ruby

!!!
%html
  %head
    %title= page_title app: 'My App'
    = stylesheet_link_tag "pdf"
  %body
    = yield

```

and finally, I have a file pdf.css file in app/assets/stylesheets.

By setting raise_on_request_failure to true, I got the following error: 
`"#<Grover::JavaScript::RequestFailedError: net::ERR_ABORTED at http://example.com/assets/pdf-b4394a610268cf28d98e5ef256be9e3db28862f5993e7458584da1b33530afa0.css>"`

How would you manage your development environment?

**Comment by abrom** [comment]
Hi @jetienne

Please have a read of the documentation regarding relative paths:

https://github.com/Studiosity/grover#relative-paths

Put simply, when rendering the HTML using Puppeteer a display URL must be provided. If you don't provide one, Grover will default to using `http://example.com`. That's why you're seeing the error with the asset attempting to load from example.com!

You have two options:
1) specify the `display_url` eg `display_url: 'http://localhost:3000'`
2) replace the relative asset URLs with absolute URLs eg:
```
absolute_html = Grover::HTMLPreprocessor.process relative_html, 'http://localhost:3000/', 'http'
```
