### ISSUE TITLE
Saved PNG is not transparent using omitBackground

### ISSUE THREAD

**Issue by darylpdavies** [Studiosity/grover#200]
I'm trying to make use of Puppeteer's property "omitBackground".

But all images are being returned with a white background. Not sure where this is failing, does Grover to_png include alpha channel to allow for transparency?

```
options = {
  endpoint: "...",
  viewport: {
    omit_background: true
  },
  full_page: true
}
```

This is the CSS on my page:

```
body {
  background-color: transparent !important;
}
```

**Comment by abrom** [comment]
I'm not entirely sure why you're passing `omit_background` in via the `viewport` option?? The Puppeteer `Page.setViewport` method does not support that option so it's going to be ignored. See https://pptr.dev/api/puppeteer.page.setviewport

I suspect you'd want that option at the root of the options so that it's passed through to the [pdf](https://pptr.dev/api/puppeteer.page.pdf) (ie `to_pdf`) or [screenshot](https://pptr.dev/api/puppeteer.page.screenshot) (ie `to_png`) methods (see the definitions of `PdfOptions` and `ScreenshotOptions` respectively. ie:
```
options = {
  endpoint: "...",
  omit_background: true,
  full_page: true
}
```

Grover is for the most part just a wrapper around the Puppeteer library, which itself is a wrapper around the Chrome browser. You can get Grover to behave like viewing the page in Chrome with the `emulate_media: 'screen'` option.. otherwise it will behave like what you'd get if you try print the page in Chrome 😉 

Can you try the above, and possibly include a screenshot of what you're expecting vs what you're getting so I can better understand the problem and what you're trying to achieve.

**Comment by daryld212** [comment]
@abrom thank you, that was 100% it.

Works perfectly, and appreciate the advice about using `emulate_media` options, makes a big difference to the output.

**Comment by abrom** [comment]
Yes, the default is to use `'print'` and by default that media type does change the behaviour of images in general to try "save ink" and to generally make things look better on paper.
