### ISSUE TITLE
Syntax error in processor.rb

### ISSUE THREAD

**Issue by nicksterious** [Studiosity/grover#214]
This is on Rails 6.1 with Ruby 3. Puppeteer is installed.

```
bash-5.1# rails c
Loading development environment (Rails 6.1.7.3)
irb(main):001:0> grover = Grover.new('https://google.com')
=> #<Grover:0x101740 @url="https://google.com">
irb(main):002:0> png = grover.to_png
/usr/local/bundle/gems/grover-1.1.5/lib/grover/processor.rb:54:in `parse_package_error': SyntaxError: Unexpected token '??=' (Grover::Error)
irb(main):003:0> grover = Grover.new('https://www.yahoo.com')
=> #<Grover:0x101760 @url="https://www.yahoo.com">
irb(main):004:0> png = grover.to_png
/usr/local/bundle/gems/grover-1.1.5/lib/grover/processor.rb:54:in `parse_package_error': SyntaxError: Unexpected token '??=' (Grover::Error)

```

**Comment by abrom** [comment]
hi @nicksterious 

The error message you're seeing is coming from Puppeteer itself. That's because you appear to be using a version of node < v14 when support for the null coalescing assignment operator was added (ie `??=`).

You have two options.. use a really old version of puppeteer (grover "should" work with every version), or update your node version to something modern (and supported by puppeteer!).

According to the Puppeteer documentation: 
> Puppeteer follows the latest [maintenance LTS](https://github.com/nodejs/Release#release-schedule) version of Node.
thus you "should" be using node v20+ 😄 

HTH
