### ISSUE TITLE
How to save pdf?

### ISSUE THREAD

**Issue by marcuxyz** [Studiosity/grover#238]
Hi,
thanks for providing the gem

How to save pdf, using method `.save`?

![Screenshot 2024-05-29 at 13 32 37](https://github.com/Studiosity/grover/assets/9499562/fa6b57a1-996d-41bc-8cf4-55cf8bce44fb)

**Comment by abrom** [comment]
Hi @marcuxyz 

Please read the [Usage](https://github.com/Studiosity/grover?tab=readme-ov-file#usage) documentation. There is no `save` method because Grover supports many output formats. Instead there is `to_pdf`, `to_png`, `to_jpeg` and `to_html`. It sounds like you want `.to_pdf`

Always a good idea to read the documentation first 😉
