### ISSUE TITLE
how to change the viewport size in ruby

### ISSUE THREAD

**Issue by perljuls** [Studiosity/grover#26]
// reports_controller.rb
```
def pdf
    pdf_html = ActionController::Base.new.render_to_string(template: 'reports/pdf.html.erb', layout: 'pdf' )

    pdf = Grover.new(pdf_html, {
      format: 'A4' //dynamic 
    }).to_pdf
end
```

//grover.rb

```
Grover.configure do |config|
  config.options = {
    emulate_media: 'screen',
    cache: false,
    print_background: true,
    prefer_css_page_size: true,
    # timeout: 0 # Timeout in ms. A value of `0` means 'no timeout'
  }
end
```

I tried pdf.setViewPort() but I think it is for page = ..browser something

**Comment by abrom** [comment]
Good question @perljuls 

Unfortunately I haven't added that in just yet. It's available in the puppeteer API on the page object:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetviewportviewport

Interestingly, I was hitting up on the need to have that in place no more than 30 minutes ago! I'll likely look to add it in for the next release

**Comment by abrom** [comment]
FYI this has been added in #28

You can configure it either via the global configuration, in the `Grover` initialiser or if you're using the middleware, via meta options

I'll roll a release with this soon

**Comment by perljuls** [comment]
Thanks :)

**Comment by willkoehler** [comment]
Is it possible to set the viewport size with a `<meta>` tags? Ex:

```
<meta name="grover-viewport-width" content=640>
<meta name="grover-viewport-height" content=480>
```

This doesn't work because 640 and 480 are converted to strings and puppeteer throws an error "Protocol error (Emulation.setDeviceMetricsOverride): Invalid parameters width: integer value expected; height: integer value expected"

(Asking here because it comes up when searching, so hopefully that will help others benefit from the answer)

**Comment by abrom** [comment]
Suggest create a new issue for this @willkoehler, but yes definitely possible. Something I'd already done for the `scale` attribute: https://github.com/Studiosity/grover/blob/7dc5056b5de25c1a885684dcc7bfa260530614a5/lib/grover.rb#L310

You're welcome to create a PR for it, otherwise I can take a look when I get some time.
