### ISSUE TITLE
How to actually display headers and footers?

### ISSUE THREAD

**Issue by altjx** [Studiosity/grover#55]
Hi guys,

Loving this gem and so far I've gotten everything narrowed down. The only thing I cannot figure out is how to display header and footer. Here's my current options:

```
          grover_options = {
            format: 'Letter',
            full_page: true,
            prefer_css_page_size: false,
            emulate_media: 'screen',
            cache: false,
            timeout: 0, # Timeout in ms. A value of `0` means 'no timeout'
            launch_args: ['--font-render-hinting=medium', '--no-sandbox'],
            margin: { top: 36, right: 36, bottom: 20, left: 36 },
            print_background: true,
            scale: 0.75,
            # display_header_footer: true
            # footer_template: render_to_string template: 'common/report_templates/shared/report_footer.html.erb', layout: false
          }
```

However, I don't even know if `display_header_footer` is in the right format as I just discovered in a recent issue that my `print_background` statement was incorrect (it was `printBackground` as shown in the API).

Other than the API (which the options there are actually formatted differently when using this gem), is there any other place for documentation so that I can understand what options/arguments should be provided so that it works properly when it converts over to the API?

_**EDIT**_: Here's what I've got thus far now:

```
          header_template = render_to_string template: 'common/report_templates/shared/report_header.html.erb', layout: false
          footer_template = render_to_string template: 'common/report_templates/shared/report_footer.html.erb', layout: false

          grover_options = {
            format: 'Letter',
            full_page: true,
            prefer_css_page_size: false,
            emulate_media: 'screen',
            cache: false,
            timeout: 0, # Timeout in ms. A value of `0` means 'no timeout'
            launch_args: ['--font-render-hinting=medium', '--no-sandbox'],
            margin: { top: 36, right: 36, bottom: 20, left: 36 },
            print_background: true,
            scale: 0.75,
            display_header_footer: true,
            footer_template: footer_template,
            header_template: header_template            
          }
```

However, it looks like the footer and header are extremely tiny:

![Screen Shot 2020-05-19 at 5 05 35 PM](https://user-images.githubusercontent.com/4023423/82378355-f59c0680-99f2-11ea-9951-4b973538aa20.png)

Here are the contents of my footer:

```
 Page <span class="pageNumber"></span> of <span class="totalPages"></span>
```

I tried wrapping that around `<font size="300pt">` but no luck

_**EDIT**_

I've now changed the footer to this:

```
 <span style="font-size: 30pt">Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
```

And it looks like this:

![Screen Shot 2020-05-19 at 5 09 25 PM](https://user-images.githubusercontent.com/4023423/82378662-7eb33d80-99f3-11ea-8dd5-dbb099f6d6b7.png)

Sorry for the multiple edits, just trying to simply get a basic header and footer going but seems to be having issues. Now it looks like the word "page" is cut off. not sure how to go about that

_**Conclusion**_

After numerous tests (even just using puppeteer itself), it seems that the footer doesn't get displayed correctly until its the last page, and I can't render images in the header as they show as just the block when an image doesn't load properly..

Can you confirm that there isn't anything I can do to solve this with grover?

**Comment by abrom** [comment]
Sorry if the documentation isn't very clear on that front. You can take all of the options available here: https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagepdfoptions

but just change them from camelcase `footerTemplate` etc to snakecase `footer_template`. Looks like you've figured that part out!

Regarding the footer content, It is definitely something lacking in the Puppeteer documentation as well as the Grover documentation. In short, Chromium has some bonkers defaults for font sizes. You can see the source of the "print" view, which is what Chromium uses to create the PDFs here:

https://chromium.googlesource.com/chromium/src/+/lkgr/components/printing/resources/print_header_footer_template_page.html

You can see there are a bunch of classes that you can add to style your footer, but you can of course add other styles! By using the specific classes it also allows you to "inject" the various values (date, title, url, page number and total pages) into your header/footer.

The default header template is:
```
<div class='date text left'></div><div class='title text center'></div>
```

The default footer template is:
```
    <div class='url text left grow'></div>
    <div class='text right'><span class='pageNumber'></span>/<span class='totalPages'></span></div>
```

So.. the important things you'll likely want to do it wrap your footer content in a div with the `grow` class, as well as `left`, `center` or `right` (depending on how you want it aligned).

From there you can use the `text` class to set up a default `8px` font, but you can of course override that however you want. 

A few notes from the Puppeteer documentation regarding header and footer templates:

1. Script tags inside templates are not evaluated.
2. Page styles are not visible inside templates.

That isn't to say you can't add styles in the templates themselves, it's just that the styles in your page are isolated, and will not 'bleed' into the header/footer, so you need to define those styles in the actual header/footer templates themselves.

```
<div class="center grow" style="font-size=20px">LARGE FOOTER</div>
```

Should work just fine.

Of course you will likely also need to factor in things like the `top_margin` (for the header) and `bottom_margin` (for the footer) if you're wanting to have really large text displayed! Otherwise your content will be clipped.

**Comment by altjx** [comment]
Thanks so much @abrom. Got it all knocked out. Much appreciated!
