### ISSUE TITLE
"undefined method `close' for nil:NilClass" on Heroku

### ISSUE THREAD

**Issue by nicolasrouanne** [Studiosity/grover#65]
### Description
When trying to generate a PDF on Heroku I get the following error
```
NoMethodError (undefined method `close' for nil:NilClass)
```

This error happens when running `Grover.new(some_html).to_pdf`

### Heroku configuration
I use the [`jontewks/puppeteer` buildpack](https://github.com/jontewks/puppeteer-heroku-buildpack), which is set to run prior the `ruby` buildpack.
<img width="835" alt="Screen Shot 2020-06-22 at 11 14 45" src="https://user-images.githubusercontent.com/12157019/85270468-9f9b0280-b479-11ea-821c-ddbf8e0f2470.png">

It seems correctly installed when looking in the build logs. I also set `GROVER_NO_SANDBOX=true` in env variables.
<img width="810" alt="Screen Shot 2020-06-22 at 11 14 54" src="https://user-images.githubusercontent.com/12157019/85270493-a45fb680-b479-11ea-8524-ae9164123f88.png">

Grover runs correctly on my Mac though w/ puppeteer installed.

> Don't know wether it's a `grover` or buildpack related issue, sorry if not appropriate for this repo.

### Versions
jontewks/puppeteer: 1.1.7
grover: 0.12.1

**Comment by abrom** [comment]
Do you have any further details about the stack trace? (ie `<your error>.backtrace`)

I can't say I've used Grover on Heroku. The documentation was added by @koenhandekyn and they might be able to add some insight.

Out of interest, does it work for you if you use v0.11.4 ? The earlier version used the Schmooze library for calling out to NodeJS and that code *should* be the only place that `.close` is called. The code in 0.12.1 was practically lifted from the Schmooze library verbatim so that *shoudn't* be the issue, but will need some more details before I could really say either way.

**Comment by nicolasrouanne** [comment]
Unfortunately this is the only stack trace I get
```
irb(main):006:0> Grover.new('<html><p>Foo</p></html>').to_pdf
Traceback (most recent call last):
        2: from (irb):5
        1: from (irb):6:in `rescue in irb_binding'
NoMethodError (undefined method `close' for nil:NilClass)
```

Will try downgrading grover to `v0.11.4`

**Comment by abrom** [comment]
Right.. but you can get the backtrace by catching the exception then dumping it:
```
Grover.new('<html><p>Foo</p></html>').to_pdf rescue puts $!.backtrace; nil
```

**Comment by nicolasrouanne** [comment]
With `grover` in v0.11.4

```
irb(main):001:0> Grover.new('<html><p>Foo</p></html>').to_pdf
Traceback (most recent call last):
        1: from (irb):1
Errno::ENOENT (No such file or directory - node)
```
There's obviously something I'm doing wrong 🤔

**Comment by abrom** [comment]
Right.. that makes sense. Grover is trying to launch `node` but fails because it's not available resulting in the exception. Problem is that when the exception occurs Grover is trying to call `close` on the NodeJS process io channels.. which don't exist yet. Doh

Definitely a bug, but the root issue here is that you don't have `node` installed ;)

**Comment by nicolasrouanne** [comment]
> Definitely a bug, but the root issue here is that you don't have node installed ;)
Isn't the puppeeter buildpack supposed to do that? In that case I should open an issue on their repo.

**Comment by abrom** [comment]
Hmm not per my understanding of how the Heroku buildpack system works. For a Ruby app you'd likely need to include it, as well as the nodejs one. See https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app

Happy to accept a PR to update the README to make the process a bit clearer!

**Comment by nicolasrouanne** [comment]
OK, it seems clearer now. I thought the puppeeter buildpack would check for node and install it if need be. But that's obviously a wrong assertion.

Will gladfully provide a PR to try to clarify this.

**Comment by nicolasrouanne** [comment]
Indeed, with the correct environment it works like a charm 🤦 

<img width="1254" alt="Screen Shot 2020-06-22 at 11 48 56" src="https://user-images.githubusercontent.com/12157019/85273820-67e28980-b47e-11ea-88cb-6468b354c632.png">
