### ISSUE TITLE
Add clarification in the docs on how to use with Rails

### ISSUE THREAD

**Issue by DaniG2k** [Studiosity/grover#74]
I've been trying to use grover with Rails 6 but am having a bit of a hard time.

Would it be possible to flesh out the explanation on how to use grover with Rails in the README?

Say I have:

- `app/views/layouts/pdf.html.slim`
- `app/views/models/pdf.html.slim` (inherits the layout from the above)

In my controller action:

```ruby
def show
  respond_to do |format|
    format.html
    format.pdf do
      html = ModelsController.new.render_to_string({
        template: 'models/pdf',
        layout: 'pdf',
        locals: { :@model => model }
      })
      pdf = Grover.new(html, { format: 'A4' }).to_pdf
      render pdf: pdf
    end
  end
end
```

gives a missing template error.
If I use `render pdf` instead, I get a path name contains null byte error.

What's the correct way to generate the pdf from a controller in Rails?

**Comment by abrom** [comment]
Well there are so many ways to render content in Rails I'm not sure it's necessarily something for the Grover Readme.

See https://api.rubyonrails.org/classes/ActionController/DataStreaming.html#method-i-send_file on how to use the `send_file` (or possibly `send_data`) helper method.

You'd likely use it as such:

```
send_file pdf, filename: 'my_pdf.pdf', type: 'application/pdf', disposition: 'inline'
```

Obviously the disposition is doing to come down to whether you're wanting to display the PDF in the browser, or indicate that the browser should show the file save dialog etc.

You could also use something like:
```
render body: pdf, content_type: 'application/pdf'
```
It just won't send the file headers etc, but obviously gives you more control over the response (although I can't think of much of reason why you'd want this!). 

The reason you'd get the missing template error is because the `render` method does not know how to deal with just passing `pdf:` argument. That's not a thing in Rails so it's complaining because it's expecting you to have provided the name of a template, file or content (ie via `partial:`, `file:`, `inline:`, `plain:`, `html:`, `json:` or `body:`). When you pass it just the pdf (ie `render pdf`) it's assuming that the second argument is the name of the partial to render. Given it's really an object I can't say how Rails would deal with that.. possibly just ignoring it and rendering nothing (ie "null byte error" like you said).

Unrelated, but regarding your code to render the template as HTML, I'd question why you're instantiating a new controller for this?
```
html = render_to_string .....
```
should work just fine!

**Comment by DaniG2k** [comment]
Thanks for that. I've gotten it partially working with:

```ruby
class ModelsController < ApplicationController
  def show
    respond_to do |format|
      format.html
      format.pdf do
        html = render_to_string({
          template: 'models/show',
          layout: 'pdf',
          locals: { :@model => model }
        })
        pdf = Grover.new(html, { format: 'A4' }).to_pdf
        Tempfile.create do |tmp|
          tmp.binmode
          tmp.write(pdf)
          tmp.rewind
          tmp.close
          send_data(
            File.open(tmp.path, 'rb').read,
            type: 'application/pdf',
            filename: "test.pdf",
            disposition: 'inline'
          )
        end
      end
    end
  end
end
```

However, there seems to be a problem with the assets. None of the styles are displaying (they are being served by Webpacker). These work fine in the actual app.

Am I missing something? 🤔

**Comment by abrom** [comment]
Yes, you've likely got **relative** paths in your HTML pointing to assets (CSS, JS, images). By default, if you don't specify it explicitly, Chromium will assume the `display_url` of `http://example.com`. This will of course result in 404 results for all assets in your page!

You need to either pass grover a `display_url` (which would be what would display in your footer or for any link tags in your content), AND/OR pass the rendered HTML string into the HTML Preprocessor to convert the relative paths to absolute paths.

See https://github.com/Studiosity/grover#relative-paths

Per the documentation, the reason you may want to specify the `display_url` AND pre-process the relative paths would be if your server was behind some sort of NAT or firewalling etc. You could pass `https://my-domain.com` or what ever as the `display_url` then use
```
absolute_html = Grover::HTMLPreprocessor.process relative_html, 'http://127.0.0.1/', 'http'
```
or similar (on the content returned from `render_to_string`) and before passing it to Grover.

This would save sending those requests "out" through your infrastructure then back in again.

Of course once thing to be especially aware of is that this will result in additional requests on your server!! You will have one request ongoing for the initial PDF request.. then possibly 2 at a time for the assets (depending on how Chromium has been configured). So you'd likely want to make sure you've got AT LEAST 3 workers on your server machine (even in development). Otherwise it'll look like your request has hung, simply because the server it waiting for workers to become available ;)

**Comment by abrom** [comment]
Also, why are you writing the PDF to a file, then reading it back in again?

This should hold true: `pdf == File.open(tmp.path, 'rb').read`

As such you can just call directly to `send_data` (or `send_file`) with `pdf` as the data ;)

**Comment by dvergeylen** [comment]
I've discovered `grover` today migrating from `wicked_pdf` and it's working like a charm! 👌

I however went through the same confusion as DaniG2k and thought it could benefit others to share the solution I ended up with:

Generate a pdf from a controller method by rendering its corresponding view:
```ruby
class UsersController < ApplicationController
def export
    @user = ...

    html_relative = UsersController.render(
      template: 'users/export',
      layout: 'pdf',
      assigns: { user: @user }
    )
    base_url = "http://localhost:3000/"
    html_absolute = Grover::HTMLPreprocessor.process html_relative, base_url, "http"
    pdf = Grover.new(html_absolute, {
      format: 'A4', 
      display_url: base_url
    }).to_pdf

    send_data pdf, type: 'application/pdf; charset=binary', filename: "test.pdf"
  end
end
```
Notice the trailing `/` in `base_url`. You have to set `display_url` option **and** use the preprocessor.

The preprocessor will prefix your assets path with `base_url` *but* this won't work for url in your stylesheets (took me a while to figure this out). I ended up adding inline a `<style>` markup with the few classes having url statements.

If your stylesheets aren't loaded, it might be because Grover loads with `emulate_media: 'screen'` option by default and you missed to add `media: "screen"` or `media: "all"` to your stylesheet import (took me a while to figure this out also, "part" of my style was loaded):

```html
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= stylesheet_link_tag "application", media: "all" %>
 </head>
...
```

Hope this helps!

**Comment by k2director** [comment]
First of all, THANK YOU to the Grover team for making and supporting this gem. And thank you to Dvergeylen for the Export code sample, which got me on my way. Now I just have to figure out why Bootstrap styles aren't included in the export...will probably open an issue...
