### ISSUE TITLE
Emojis not working

### ISSUE THREAD

**Issue by matixmatix** [Studiosity/grover#88]
When I render inline HTML with emojis, the PDF contains odd characters instead of emojis.

My HTML:

![image](https://user-images.githubusercontent.com/273660/98358079-72b14b80-2026-11eb-9753-aaf519c16144.png)

PDF, generated using `Grover.new(File.read("test.html")).to_pdf("test.pdf");`

![image](https://user-images.githubusercontent.com/273660/98358148-8e1c5680-2026-11eb-83b9-286cc6fde49a.png)

Any clue why this would happen?

**Comment by abrom** [comment]
This appears to be an encoding/charset problem, and it's a problem with how Chrome is interpreting your page, not Grover. You will get the same result if you open the `test.html` in a browser. It will come down to how that browser is going to read the bytes!

Chrome and Safari render it "strangely" and Firefox appears to render the emoji. The root of this is because emoji's require 2+ bytes to describe them, and the browser is simply rendering each of those separate bytes on the page.

Anyway, simple answer.. specify the charset in the head tag. i.e.

```
Grover.new(%{<html><head><meta charset="UTF-8" /></head><body>😀</body></html>}).to_pdf('test.pdf');
```

HTH

**Comment by matixmatix** [comment]
Beautiful, it works. Thank you @abrom! Thanks for making Grover.
